development:
  adapter: postgresql
  encoding: utf8
  database: monster_dev
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/monster_test
  pool: 5
  timeout: 5000
  username: monster

production:
  adapter: postgresql
  encoding: utf8
  database: monster_production
  pool: 5
  timeout: 5000
